# Generated by Django 3.1.2 on 2021-11-30 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=255)),
                ('Apt_Suite', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Date', models.DateField()),
                ('ModifiedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 760262, tzinfo=utc))),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 760262, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='')),
                ('ModifiedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 760262, tzinfo=utc))),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 760262, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='RatesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('ModifiedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 701981, tzinfo=utc))),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 701981, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(max_length=200)),
                ('Pub_Date', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField()),
                ('ModifiedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 759265, tzinfo=utc))),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 40, 12, 759265, tzinfo=utc))),
                ('Category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ratescategory')),
            ],
        ),
    ]
