# Generated by Django 3.2.4 on 2021-11-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ratescategory_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='Category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ratescategory'),
        ),
    ]
