# Generated by Django 3.2.4 on 2021-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_rates_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='Pub_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
